engineStrict: true
allowBuilds:
  esbuild: true
  '@carbon/colors': true
  '@carbon/feature-flags': true
  '@carbon/grid': true
  '@carbon/layout': true
  '@carbon/motion': true
  '@carbon/styles': true
  '@carbon/themes': true
  '@carbon/type': true
  '@ibm/plex': true
  '@ibm/plex-mono': true
  '@ibm/plex-sans': true
  '@ibm/plex-serif': true
  '@parcel/watcher': true
  carbon-components-svelte: true
  '@ibm/plex-sans-arabic': false
  '@ibm/plex-sans-devanagari': false
  '@ibm/plex-sans-hebrew': false
  '@ibm/plex-sans-thai': false
  '@ibm/plex-sans-thai-looped': false
  libxmljs2: true
